# modules/adapters/system-manager.nix
#
# The activation adapter for `nixdeploy.backend = "system-manager"` -- Nix managing a slice
# of a FOREIGN distro's `/etc` and systemd units (numtide/system-manager), not a NixOS
# system. This is nixdeploy's whole reason for a per-backend adapter registry rather than a
# single "run switch-to-configuration" engine: the receiver on this backend is a plain
# Ubuntu/Debian box that happens to have Nix installed, and neither `switch-to-configuration`
# nor `/run/current-system` mean anything there.
#
# Every mechanism this file relies on was read directly out of numtide/system-manager's own
# source (main branch, checked while writing this file) rather than assumed -- the exact
# CLI surface and on-disk paths are cited inline below, because getting one of them wrong
# here fails silently (a machine that reports itself converged while running nothing, or a
# `rollback` that quietly does not exist) rather than loudly.
#
# THE ENGINE SHIPS INSIDE THE CLOSURE -- NO SEPARATE INSTALL ON THE RECEIVER
#
# A built system-manager profile is not just `/etc` files and systemd units: its own
# top-level derivation (`toplevel` in `nix/lib.nix`) bundles `bin/system-manager-engine`
# (the privileged activation binary, wrapped with `nix` already on its PATH) plus three
# tiny self-locating wrapper scripts generated by `nix/modules/default.nix`'s
# `build.scripts`: `bin/activate`, `bin/register-profile` (its store derivation is literally
# named `register-profile`, not `register`) and `bin/deactivate`. Each resolves its OWN
# store path at run time via `dirname $(realpath $(dirname "$0"))` and calls
# `system-manager-engine <verb> --store-path <that path>` -- so `$target/bin/activate` and
# `$target/bin/register-profile` are exactly as self-contained as NixOS's
# `$target/bin/switch-to-configuration`: nothing needs to be pre-installed on this machine
# beyond Nix itself, and there is nothing for this adapter to point at outside the closure
# it was already handed.
#
# TWO SEPARATE STEPS, IN THE SAME ORDER THE REAL "switch" TAKES
#
# The engine's own low-level verbs are genuinely separate: `activate` only writes `/etc`
# files and starts/reloads systemd units (`crates/system-manager-engine/src/activate.rs`);
# nothing about it touches what generation is "current." Recording that is `register`'s
# entire job (`crates/system-manager-engine/src/register.rs`): `nix-env --profile
# /nix/var/nix/profiles/system-manager-profiles/system-manager --set <path>` (an ordinary
# nix-env generation, same primitive `nixos-rebuild` and `darwin-rebuild` use on their own
# system profiles) plus a supplementary GC root at
# `/nix/var/nix/gcroots/system-manager-current`. The higher-level `system-manager switch`
# CLI subcommand (`crates/system-manager/src/main.rs`, `Action::Switch`) calls
# `invoke_engine_register` THEN `invoke_engine_activate`, in that order, against the SAME
# store path -- `activateScript` below reproduces exactly that order for the same reason:
# skipping the register step would still make the machine run the requested closure right
# now, but no rollback (here or via a human's own `nix-env --rollback` on this profile)
# could ever get back to it, and its files would lose GC protection at the next `nix-store
# --gc` (see the profile-and-GC-root paragraph below for why that risk is smaller than it
# sounds, but still real).
#
# WHY `rollback` IS REAL HERE, NOT `null`
#
# system-manager ships no built-in "rollback" subcommand of its own -- but `register`
# above is a PLAIN nix-env generation on an ordinary nix-env profile, and nix-env's
# `--rollback` flag works on any profile, regardless of which tool populated its
# generations. That is the exact primitive NixOS's `nixos-rebuild --rollback` and
# nix-darwin's `darwin-rebuild --rollback` are themselves built on (see `nixos.nix` and
# `nix-darwin.nix` in this same directory) -- this is not a guess or an invented mechanism,
# it is the same verified Nix primitive applied to system-manager's own profile path.
#
# Skipping `register-profile` on the way back (mirroring `nixos-rebuild`'s and
# `darwin-rebuild`'s own rollback code, neither of which re-registers after rolling back)
# is safe for the GC-root concern too: `nix-store`'s garbage collector treats EVERY path
# reachable from anywhere under `/nix/var/nix/profiles/` as a root unconditionally, with no
# extra registration needed -- `register`'s own `GCROOT_PATH` symlink
# (`/nix/var/nix/gcroots/system-manager-current`) is additional, human-discoverable
# protection on top of that, not the only thing standing between a rolled-back generation
# and collection. A plain `nix-env --rollback` on the profile is already enough to keep the
# path it points at alive.
#
# THE OTHER TWO VERBS: `schedule` AND `nixSettings`
#
# `schedule` is shared with `nixos.nix` via `systemd-scheduling.nix` in this directory --
# system-manager's whole premise is that the foreign distro already runs systemd, and it
# builds `systemd.services`/`systemd.timers` on the same nixpkgs unit-option definitions
# NixOS does, so the service/timer pair is identical and factoring it out keeps the two from
# drifting apart on the hardening reasoning that file spells out.
#
# `nixSettings` is where this backend genuinely diverges, and it diverges by REFUSING. See
# its own comment at the bottom of this file.
{ config, lib, pkgs, ... }:
let
  cfg = config.nixdeploy;

  scheduling = import ./systemd-scheduling.nix { inherit lib; };
  publisherScheduling = import ./publisher-systemd-scheduling.nix { inherit lib; };

  # `systemd` and NOTHING else -- the shortest of the three `trees` lists in this directory,
  # and the difference is the whole point of this backend: system-manager manages a slice of a
  # foreign distro, and `nix` is not in that slice. See apply.nix for what the list is for,
  # and `nixSettings` at the bottom of this file for what happens when someone sets a knob
  # that would have needed it.
  forward = (import ./apply.nix { inherit lib; }).forward {
    adapter = "system-manager";
    trees = [ "systemd" ];
  };

  profileDir = "/nix/var/nix/profiles/system-manager-profiles";
  profileName = "system-manager";
  profilePath = "${profileDir}/${profileName}";

  # Same absolute-store-path convention as nixos.nix and nix-darwin.nix in this directory:
  # a bare tool name resolved off whatever PATH the receiver's systemd unit happens to have
  # fails at RUN time with "command not found," misread by everything downstream as "the
  # thing being checked is broken" rather than "this command never even started." Real,
  # already-paid-for multi-day silent outage in this family; not a hypothetical.
  nixEnv = "${pkgs.nix}/bin/nix-env";
  readlink = "${pkgs.coreutils}/bin/readlink";

  # Single definition of "what generation is registered right now," reused by the
  # standalone `currentPath` command and by `applyAndVerify`'s own disambiguation -- see
  # nixos.nix's identical comment on `readCurrentSystem` for why one definition, not two,
  # is load-bearing here.
  #
  # UNLIKE the nixos/nix-darwin backends, "never activated yet" is a real, expected case
  # here, not a defensive-only guard: this backend targets a foreign distro that may have
  # had Nix and this adapter's own receiver installed by some bootstrap step entirely
  # outside system-manager (that bootstrap IS what this adapter exists to replace with a
  # real activation), so `profilePath` genuinely may not exist the first time this ever
  # runs. `src/activate.rs`'s `run_capturing` (the receiver's own caller of this command)
  # treats a non-zero exit OR empty trimmed stdout as a hard error that aborts the entire
  # run -- on exactly the tick a correct answer matters most, a fresh machine's very first
  # convergence attempt. Printing a fixed sentinel that can never collide with a real
  # `/nix/store/...` path keeps that first tick from erroring out: it reads as "not
  # currently running the manifest's target," which is simply true, and lets the receiver
  # proceed to activate for the first time.
  readCurrentProfile = ''
    if [ -e ${profilePath} ]; then
      ${readlink} -f ${profilePath}
    else
      echo nixdeploy-uninitialized
    fi
  '';

  currentPathScript = pkgs.writeShellScript "nixdeploy-system-manager-current-path" ''
    set -u
    ${readCurrentProfile}
  '';

  # Runs `$1/bin/activate` and reports whether the machine ended up running it --
  # deliberately does NOT call `register-profile`: shared by `activate` (which registers
  # first, see below) and `rollback` (which must not re-register, see this file's header).
  # No `set -e`: `activate`'s own exit code is wanted as a diagnostic, not as something
  # allowed to abort this script before the disambiguation runs.
  applyAndVerifyScript = pkgs.writeShellScript "nixdeploy-system-manager-apply-and-verify" ''
    set -u
    target="''${1:?nixdeploy-system-manager-apply-and-verify: no store path given}"

    if [ ! -x "$target/bin/activate" ]; then
      echo "nixdeploy: system-manager: $target/bin/activate is missing or not executable -- not a system-manager profile closure?" >&2
      exit 1
    fi

    "$target/bin/activate"
    activate_status=$?

    current="$(${readCurrentProfile})"
    if [ "$current" = "$target" ]; then
      # As with nixos.nix's switch-to-configuration: a non-zero $activate_status here
      # (some unit this profile manages failed to start, an /etc file could not be
      # written) is a real problem already reported on stderr above, but it does not mean
      # the machine is not running $target -- register-profile (run before this, by
      # activateScript below) already advanced the profile to $target regardless of
      # whether every managed unit came up clean, the same way NixOS's own
      # /run/current-system advances before unit restarts are even attempted.
      exit 0
    fi

    if [ "$activate_status" -eq 0 ]; then
      echo "nixdeploy: system-manager: activate exited 0 but ${profilePath} ($current) is not $target" >&2
    else
      echo "nixdeploy: system-manager: activate exited $activate_status and ${profilePath} ($current) is still not $target" >&2
    fi
    exit 1
  '';

  activateScript = pkgs.writeShellScript "nixdeploy-system-manager-activate" ''
    set -u
    target="''${1:?nixdeploy-system-manager-activate: no store path given}"

    # Best-effort, not fatal -- see this file's header: skipping this would still let
    # applyAndVerifyScript below make the machine run $target right now, it would just
    # leave the generation history (and therefore `rollback`) unable to get back to it.
    if [ -x "$target/bin/register-profile" ]; then
      if ! "$target/bin/register-profile"; then
        echo "nixdeploy: system-manager: $target/bin/register-profile failed -- proceeding to activate anyway, but a later rollback will not be able to return to this generation" >&2
      fi
    else
      echo "nixdeploy: system-manager: $target/bin/register-profile is missing -- proceeding to activate anyway, but ${profilePath} will not advance and a later rollback will not be able to return to this generation" >&2
    fi

    exec ${applyAndVerifyScript} "$target"
  '';

  rollbackScript = pkgs.writeShellScript "nixdeploy-system-manager-rollback" ''
    set -u

    if ! ${nixEnv} --rollback -p ${profilePath}; then
      echo "nixdeploy: system-manager: nix-env --rollback -p ${profilePath} failed -- likely no previous generation to roll back to" >&2
      exit 1
    fi

    target="$(${readlink} -f ${profilePath})"
    exec ${applyAndVerifyScript} "$target"
  '';
in
{
  # Guarded on `cfg.backend` rather than assumed from being imported at all -- see
  # nixos.nix's identical comment for why a plain assignment (not mkDefault) is the point:
  # two adapters imported into the same evaluation by mistake should fail loudly with
  # Nix's own "conflicting definitions" error, not silently pick one.
  config = lib.mkIf (cfg.backend == "system-manager") (lib.mkMerge [
    {
      nixdeploy.receiver.activation = {
        activate = "${activateScript}";
        currentPath = "${currentPathScript}";
        rollback = "${rollbackScript}";

        schedule = scheduling.mkSchedule;

        # THIS BACKEND CANNOT HONOUR THE TWO MEMORY CEILINGS, AND SAYS SO INSTEAD OF
        # PRETENDING
        #
        # `receiver.httpConnections` and `receiver.downloadBufferSize` are daemon-side Nix
        # settings: they are read by `nix-daemon` while it substitutes, not by whoever asked
        # it to. On NixOS and nix-darwin that daemon's configuration is part of the closure
        # this module is already replacing, so setting them there is one `nix.settings`
        # entry. Here it is not. This backend manages a SLICE of a foreign distro (see this
        # file's header), whose Nix was installed and configured by that distro's own
        # installer -- which owns `/etc/nix/nix.conf`, wrote `build-users-group`,
        # `trusted-users` and `experimental-features` into it, and will write it again on its
        # next upgrade. Taking that file over from a delivery tool means either clobbering
        # settings this machine needs to have a working Nix at all, or racing an installer
        # for ownership of it; and even a perfectly-written file would not take effect
        # without restarting a `nix-daemon` this module did not install.
        #
        # So: throw. `modules/default.nix`'s own description of this verb states the rule --
        # "an adapter with nowhere to put them must FAIL rather than accept and drop them: a
        # silently-ignored ceiling is worse than no ceiling at all, because it reads as
        # protection to whoever set it." A build error naming the file to edit is a
        # two-minute fix; a ceiling that was never applied is discovered when a machine dies
        # mid-fetch.
        #
        # The empty fragment is what makes this throw REACHABLE. `forward` above emits every
        # tree in its list on every call, so `systemd` is read out of this fragment too --
        # which forces it, which fires the throw. A verb whose result nothing ever forced
        # would be a refusal nobody ever received.
        nixSettings = { httpConnections, downloadBufferSize }:
          lib.throwIf (httpConnections != null || downloadBufferSize != null) ''
            nixdeploy: backend "system-manager" cannot apply receiver.httpConnections or
            receiver.downloadBufferSize. Both are read by nix-daemon while it substitutes, and
            on this backend that daemon's configuration file (/etc/nix/nix.conf) belongs to
            the foreign distro's own Nix installation -- system-manager manages a slice of
            this machine and that file is not in it.

            Set them in that machine's own /etc/nix/nix.conf instead:

              http-connections = <n>
              download-buffer-size = <bytes>

            and restart nix-daemon there. Then leave both options unset here, so nothing
            claims to be enforcing a ceiling it cannot enforce.
          ''
            { };
      };

      nixdeploy.publisher.schedule = publisherScheduling.mkSchedule;
    }

    # See nixos.nix's identical comment: applying the verbs is separate from defining them,
    # and goes through the OPTION so that an operator's replacement wins over this file's
    # default.
    (lib.mkIf cfg.receiver.enable (lib.mkMerge [
      (forward "schedule" (cfg.receiver.activation.schedule cfg.receiver.job))
      (forward "nixSettings" (cfg.receiver.activation.nixSettings {
        inherit (cfg.receiver) httpConnections downloadBufferSize;
      }))
    ]))

    (lib.mkIf cfg.publisher.enable
      (forward "publisherSchedule" (cfg.publisher.schedule cfg.publisher.job)))
  ]);
}
